### ISSUE TITLE
No photos being taken

### ISSUE THREAD

**Issue by Ababo23** [joergmlpts/olympus-wifi#2]
Hello,

I used this script to take focus stacked images with E-M1MarkIII but when I run the code, I keep getting E-M1MarkIII is taking a photo... message and there is no picture taken. I connected the camera to my computer using a cable that came with the camera. Any help would be much appreciated.

**Comment by joergmlpts** [comment]
A browser can be used to verify that the camera is actually connected with wifi: The camera will respond to [http://192.168.0.10/DCIM](http://192.168.0.10/DCIM) with a web page. If the browser does not display the camera's web page, the camera is not yet connected with wifi and the software in this repository will not work.

This script is not for a camera connected with a cable. The camera must be connected with wify.

**Comment by Ababo23** [comment]
Thank you for quick response!
