### ISSUE TITLE
how to add manual focus

### ISSUE THREAD

**Issue by mekremil** [joergmlpts/olympus-wifi#4]
how to add manual focus

**Comment by joergmlpts** [comment]
My camera does not support manual focus. I would suggest this approach:

- Familiarize yourself with chapter [Sending Camera Commands](https://olympus-wifi.readthedocs.io/en/latest/usage.html#sending-camera-commands), get your camera's command list and find the command for manual focus.
- Explore the manual focus command thorougly with command-line options.
- Finally, add code to [liveview.py](https://github.com/joergmlpts/olympus-wifi/blob/main/src/olympuswifi/liveview.py) for manual focus.

**Comment by mekremil** [comment]
yapp... i have downloaded commandlist.xml.. but it seem no command control for manual focus like in Olympus share APK. so when i choose manual focus on camera and then connected camera through wifi, it can control focusing with button step by step. it's important for focus stacking.
thanks for the answer and great works

**Comment by mekremil** [comment]
my camera is olympus tg6
